name: test_web3dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bip39_mnemonic: ^3.0.6
  convert: ^3.1.1
  dart_bip32_bip44: ^0.2.0
  http: ^0.13.5
  web3dart: ^2.6.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
